### ISSUE TITLE
Getting error 

### ISSUE THREAD

**Issue by slefevre** [eLvErDe/museek-plus#22]
Hello! I am trying to build museek on Debian 8.5 with cmake 3.0.2. I'm getting errors saying the following:

```
$ sudo cmake . -DMUCOUS=1 -DEVERYTHING=0 -DNO_MUSEEKD=0
DECLARATIONS:
Package options: EVERYTHING, MURMUR, MUCOUS, CLIENTS, BINDINGS
Museeq options: BINRELOC, RELOAD_TRANSLATIONS
Prefix these declarations with -D and set them with either 1, 0 or a path.
Set -DEVERYTHING=1 if you want it all.
CMake Error at /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find Event (missing: Event_INCLUDE_DIRS Event_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindEvent.cmake:22 (find_package_handle_standard_args)
  NewNet/CMakeLists.txt:4 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/username/museek-plus/CMakeFiles/CMakeOutput.log".
See also "/home/username/museek-plus/CMakeFiles/CMakeError.log".
```

I was trying to build only the daemon and the cli.

Googling, I found an 8-year-old, fixed error report indicating the same errors, but it happened to be for building on BSD. http://www.museek-plus.org/ticket/145

I don't really anything about c-family languages or compiling them on *nix systems, sorry I can't be of more help. 

If you need other package versions on my system, let me know. 

Attaching the log files. 

[CMakeError.log.txt](https://github.com/eLvErDe/museek-plus/files/441530/CMakeError.log.txt)
[CMakeOutput.log.txt](https://github.com/eLvErDe/museek-plus/files/441531/CMakeOutput.log.txt)

**Comment by slefevre** [comment]
Also, this build from from the cloned repo. This is the latest commit I have in it:
```
commit bb859de32e3ae776b0fffb6acbde2240667e0c53
Merge: 4d8f291 b6c6d5c
Author: Adam Cécile <acecile@le-vert.net>
Date:   Tue Mar 15 12:10:15 2016 +0100

    Merge pull request #17 from flv0/cmake-cleanup

    Cmake cleanup

```

**Comment by flv0** [comment]
It seems you need to install libevent-dev on debian. libevent it is required to build museek as stated in the INSTALL file.

**Comment by slefevre** [comment]
That was it! Thank you : )
