### ISSUE TITLE
fails to build: NewNet/nnsocket.h:89:22: error: ‘struct event’ has no member named ‘ev_flags’

### ISSUE THREAD

**Issue by andrius4669** [eLvErDe/museek-plus#31]
system: gentoo 64bit
configure commandline:
~/museek-plus_/build $ cmake .. -DEVERYTHING=1

build log:
~/museek-plus_/build $ make
Scanning dependencies of target NewNet
[  0%] Building CXX object NewNet/CMakeFiles/NewNet.dir/nnbuffer.cpp.o
[  1%] Building CXX object NewNet/CMakeFiles/NewNet.dir/nnclientsocket.cpp.o
In file included from /home/andrius/museek-plus_/NewNet/nnclientsocket.h:24:0,
                 from /home/andrius/museek-plus_/NewNet/nnclientsocket.cpp:21:
/home/andrius/museek-plus_/NewNet/nnsocket.h: In constructor ‘NewNet::Socket::Socket()’:
/home/andrius/museek-plus_/NewNet/nnsocket.h:89:22: error: ‘struct event’ has no member named ‘ev_flags’
         m_EventData->ev_flags = 0; // This event has not been initialized
                      ^
make[2]: *** [NewNet/CMakeFiles/NewNet.dir/build.make:87: NewNet/CMakeFiles/NewNet.dir/nnclientsocket.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:86: NewNet/CMakeFiles/NewNet.dir/all] Error 2
make: *** [Makefile:128: all] Error 2

libevent version: 2.1.8
probably in new version API changed
I fixed it myself replacing `m_EventData->ev_flags = 0` with `memset(m_EventData, 0, sizeof(struct event))`.
it doesn't change meaning and works regardless if ev_flags exists or not.
will include pull request.

**Comment by holytrousers** [comment]
hey @andrius4669, i am having the same problem, so i replaced the line as you suggested but the error now becomes :
```
/home/k/bin/git/museek-plus/NewNet/nnsocket.h:90:3: error: ‘memset’ was not declared in this scope
   memset(m_EventData, 0, sizeof(struct event))
   ^~~~~~
/home/k/bin/git/museek-plus/NewNet/nnsocket.h:90:3: note: suggested alternative: ‘tzset’
   memset(m_EventData, 0, sizeof(struct event))
   ^~~~~~
   tzset
make[2]: *** [NewNet/CMakeFiles/NewNet.dir/build.make:87: NewNet/CMakeFiles/NewNet.dir/nnclientsocket.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:86: NewNet/CMakeFiles/NewNet.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
Would you be so kind to point out what's wrong ?

**Comment by andrius4669** [comment]
@holytrousers it needs `#include <string.h>` too, see referenced pull request

**Comment by holytrousers** [comment]
that's great andrius. apart from museeq (which shows a similar problem) everything compiles without errors.
However when running musetup i get this error   
```
File "/usr/local/bin/musetup", line 85
    print 'Configuration updated. Don\'t forget to restart museekd.'
                                                                   ^
SyntaxError: Missing parentheses in call to 'print'
```
Do you think this is somehow related ? seems like code is outdated ...

**Comment by andrius4669** [comment]
@holytrousers
Uh, I don't think it's related. musetup is written in python.
Maybe pull request would need rebase, I'm not sure. But it's really simple change so you could just manually apply changes by hand.

**Comment by holytrousers** [comment]
the first line in musetup calls python.
i changed it to python2 and now it works.
thank you andrius that's very kind !

**Comment by holytrousers** [comment]
@andrius4669 i know this is way out of topic but do you have a file in mucous/pymucous called utils.py ?
```
~/bin/git/museek-plus/mucous python2 setup.py build
Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    from pymucous.utils import Version
ImportError: No module named utils 
```
in mucous/MANIFEST it should be there but i can't find it ..

**Comment by andrius4669** [comment]
@holytrousers no clue, sorry.

**Comment by holytrousers** [comment]
seems like i will be stuck with the cli client for a while ^^
thanks again mate !
